#############################################################################
# Makefile for building: bin/release/Xplist
# Generated by qmake (3.1) (Qt 6.5.1)
# Project:  Xplist.pro
# Template: app
# Command: /usr/bin/qmake6 -o Makefile Xplist.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = clang
CXX           = clang++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_XML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -Wextra -fPIC -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -std=gnu++1z -Wall -Wextra -fPIC -D_REENTRANT $(DEFINES)
INCPATH       = -I. -I/usr/include/QtWidgets -I/usr/include/QtGui -I/usr/include/QtXml -I/usr/include/QtNetwork -I/usr/include/QtCore -I. -I. -I/usr/mkspecs/linux-clang
QMAKE         = /usr/bin/qmake6
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/bin/qmake6 -install qinstall
QINSTALL_PROGRAM = /usr/bin/qmake6 -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = Xplist1.0.0
DISTDIR = /home/andyvand/Downloads/Xplist/.tmp/Xplist1.0.0
LINK          = clang++
LFLAGS        = -ccc-gcc-name g++ -Wl,-rpath,/usr/lib -Wl,-rpath-link,/usr/lib
LIBS          = $(SUBLIBS) /usr/lib/libQt6Widgets.so /usr/lib/libQt6Gui.so /usr/lib/x86_64-linux-gnu/libGLX.so /usr/lib/x86_64-linux-gnu/libOpenGL.so /usr/lib/libQt6Xml.so /usr/lib/libQt6Network.so /usr/lib/libQt6Core.so -lpthread -lGLX -lOpenGL   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		MyTabBar.cpp \
		MyTabPopup.cpp \
		Plist.cpp \
		PlistDate.cpp \
		autoupdatedialog.cpp \
		codeeditor.cpp \
		comboboxdelegatebool.cpp \
		filesystemwatcher.cpp \
		mainwindow.cpp \
		domparser.cpp \
		dommodel.cpp \
		domitem.cpp \
		comboboxdelegate.cpp \
		lineeditdelegate.cpp \
		editortab.cpp \
		editortabswidget.cpp \
		commands.cpp \
		itemstate.cpp \
		myapp.cpp \
		myhighlighter.cpp \
		mytreeview.cpp \
		pugixml.cpp \
		recentfiles.cpp qrc_res.cpp \
		moc_mainwindow.cpp \
		moc_MyTabBar.cpp \
		moc_MyTabPopup.cpp \
		moc_autoupdatedialog.cpp \
		moc_codeeditor.cpp \
		moc_comboboxdelegatebool.cpp \
		moc_dommodel.cpp \
		moc_comboboxdelegate.cpp \
		moc_filesystemwatcher.cpp \
		moc_lineeditdelegate.cpp \
		moc_editortab.cpp \
		moc_editortabswidget.cpp \
		moc_myhighlighter.cpp \
		moc_mytreeview.cpp \
		moc_recentfiles.cpp
OBJECTS       = main.o \
		MyTabBar.o \
		MyTabPopup.o \
		Plist.o \
		PlistDate.o \
		autoupdatedialog.o \
		codeeditor.o \
		comboboxdelegatebool.o \
		filesystemwatcher.o \
		mainwindow.o \
		domparser.o \
		dommodel.o \
		domitem.o \
		comboboxdelegate.o \
		lineeditdelegate.o \
		editortab.o \
		editortabswidget.o \
		commands.o \
		itemstate.o \
		myapp.o \
		myhighlighter.o \
		mytreeview.o \
		pugixml.o \
		recentfiles.o \
		qrc_res.o \
		moc_mainwindow.o \
		moc_MyTabBar.o \
		moc_MyTabPopup.o \
		moc_autoupdatedialog.o \
		moc_codeeditor.o \
		moc_comboboxdelegatebool.o \
		moc_dommodel.o \
		moc_comboboxdelegate.o \
		moc_filesystemwatcher.o \
		moc_lineeditdelegate.o \
		moc_editortab.o \
		moc_editortabswidget.o \
		moc_myhighlighter.o \
		moc_mytreeview.o \
		moc_recentfiles.o
DIST          = Info.plist \
		myapp.rc \
		/usr/mkspecs/features/spec_pre.prf \
		/usr/mkspecs/common/unix.conf \
		/usr/mkspecs/common/linux.conf \
		/usr/mkspecs/common/sanitize.conf \
		/usr/mkspecs/common/gcc-base.conf \
		/usr/mkspecs/common/gcc-base-unix.conf \
		/usr/mkspecs/common/clang.conf \
		/usr/mkspecs/qconfig.pri \
		/usr/mkspecs/modules/qt_lib_3danimation.pri \
		/usr/mkspecs/modules/qt_lib_3danimation_private.pri \
		/usr/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/mkspecs/modules/qt_lib_3dcore_private.pri \
		/usr/mkspecs/modules/qt_lib_3dextras.pri \
		/usr/mkspecs/modules/qt_lib_3dextras_private.pri \
		/usr/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/mkspecs/modules/qt_lib_3dinput_private.pri \
		/usr/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/usr/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/usr/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/usr/mkspecs/modules/qt_lib_3dquickextras.pri \
		/usr/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/usr/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/usr/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/usr/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/usr/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/usr/mkspecs/modules/qt_lib_3drender.pri \
		/usr/mkspecs/modules/qt_lib_3drender_private.pri \
		/usr/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/mkspecs/modules/qt_lib_bodymovin_private.pri \
		/usr/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/mkspecs/modules/qt_lib_charts.pri \
		/usr/mkspecs/modules/qt_lib_charts_private.pri \
		/usr/mkspecs/modules/qt_lib_chartsqml.pri \
		/usr/mkspecs/modules/qt_lib_chartsqml_private.pri \
		/usr/mkspecs/modules/qt_lib_coap.pri \
		/usr/mkspecs/modules/qt_lib_coap_private.pri \
		/usr/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/mkspecs/modules/qt_lib_core.pri \
		/usr/mkspecs/modules/qt_lib_core5compat.pri \
		/usr/mkspecs/modules/qt_lib_core5compat_private.pri \
		/usr/mkspecs/modules/qt_lib_core_private.pri \
		/usr/mkspecs/modules/qt_lib_datavisualization.pri \
		/usr/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/usr/mkspecs/modules/qt_lib_datavisualizationqml.pri \
		/usr/mkspecs/modules/qt_lib_datavisualizationqml_private.pri \
		/usr/mkspecs/modules/qt_lib_dbus.pri \
		/usr/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/mkspecs/modules/qt_lib_declarativeopcua.pri \
		/usr/mkspecs/modules/qt_lib_declarativeopcua_private.pri \
		/usr/mkspecs/modules/qt_lib_designer.pri \
		/usr/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/mkspecs/modules/qt_lib_example_icons_private.pri \
		/usr/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/mkspecs/modules/qt_lib_freetype_private.pri \
		/usr/mkspecs/modules/qt_lib_gamepad.pri \
		/usr/mkspecs/modules/qt_lib_gamepad_private.pri \
		/usr/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/mkspecs/modules/qt_lib_grpc.pri \
		/usr/mkspecs/modules/qt_lib_grpc_private.pri \
		/usr/mkspecs/modules/qt_lib_gui.pri \
		/usr/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/mkspecs/modules/qt_lib_harfbuzz_private.pri \
		/usr/mkspecs/modules/qt_lib_help.pri \
		/usr/mkspecs/modules/qt_lib_help_private.pri \
		/usr/mkspecs/modules/qt_lib_httpserver.pri \
		/usr/mkspecs/modules/qt_lib_httpserver_private.pri \
		/usr/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/mkspecs/modules/qt_lib_jpeg_private.pri \
		/usr/mkspecs/modules/qt_lib_jsonrpc_private.pri \
		/usr/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/mkspecs/modules/qt_lib_labsanimation.pri \
		/usr/mkspecs/modules/qt_lib_labsanimation_private.pri \
		/usr/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		/usr/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		/usr/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		/usr/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		/usr/mkspecs/modules/qt_lib_labssettings.pri \
		/usr/mkspecs/modules/qt_lib_labssettings_private.pri \
		/usr/mkspecs/modules/qt_lib_labssharedimage.pri \
		/usr/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		/usr/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		/usr/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		/usr/mkspecs/modules/qt_lib_languageserver_private.pri \
		/usr/mkspecs/modules/qt_lib_linguist.pri \
		/usr/mkspecs/modules/qt_lib_linguist_private.pri \
		/usr/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/mkspecs/modules/qt_lib_location.pri \
		/usr/mkspecs/modules/qt_lib_location_private.pri \
		/usr/mkspecs/modules/qt_lib_mqtt.pri \
		/usr/mkspecs/modules/qt_lib_mqtt_private.pri \
		/usr/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/mkspecs/modules/qt_lib_multimediaquick_private.pri \
		/usr/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/mkspecs/modules/qt_lib_network.pri \
		/usr/mkspecs/modules/qt_lib_network_private.pri \
		/usr/mkspecs/modules/qt_lib_networkauth.pri \
		/usr/mkspecs/modules/qt_lib_networkauth_private.pri \
		/usr/mkspecs/modules/qt_lib_nfc.pri \
		/usr/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/mkspecs/modules/qt_lib_opcua.pri \
		/usr/mkspecs/modules/qt_lib_opcua_private.pri \
		/usr/mkspecs/modules/qt_lib_opengl.pri \
		/usr/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/mkspecs/modules/qt_lib_openglwidgets.pri \
		/usr/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		/usr/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/mkspecs/modules/qt_lib_png_private.pri \
		/usr/mkspecs/modules/qt_lib_positioning.pri \
		/usr/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/usr/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/mkspecs/modules/qt_lib_protobuf.pri \
		/usr/mkspecs/modules/qt_lib_protobuf_private.pri \
		/usr/mkspecs/modules/qt_lib_purchasing.pri \
		/usr/mkspecs/modules/qt_lib_purchasing_private.pri \
		/usr/mkspecs/modules/qt_lib_qml.pri \
		/usr/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		/usr/mkspecs/modules/qt_lib_qmlcore.pri \
		/usr/mkspecs/modules/qt_lib_qmlcore_private.pri \
		/usr/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/mkspecs/modules/qt_lib_qmldom_private.pri \
		/usr/mkspecs/modules/qt_lib_qmlintegration.pri \
		/usr/mkspecs/modules/qt_lib_qmlintegration_private.pri \
		/usr/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		/usr/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		/usr/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/usr/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri \
		/usr/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/usr/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		/usr/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		/usr/mkspecs/modules/qt_lib_quick.pri \
		/usr/mkspecs/modules/qt_lib_quick3d.pri \
		/usr/mkspecs/modules/qt_lib_quick3d_private.pri \
		/usr/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		/usr/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		/usr/mkspecs/modules/qt_lib_quick3dassetutils.pri \
		/usr/mkspecs/modules/qt_lib_quick3dassetutils_private.pri \
		/usr/mkspecs/modules/qt_lib_quick3deffects.pri \
		/usr/mkspecs/modules/qt_lib_quick3deffects_private.pri \
		/usr/mkspecs/modules/qt_lib_quick3dglslparser_private.pri \
		/usr/mkspecs/modules/qt_lib_quick3dhelpers.pri \
		/usr/mkspecs/modules/qt_lib_quick3dhelpers_private.pri \
		/usr/mkspecs/modules/qt_lib_quick3dhelpersimpl.pri \
		/usr/mkspecs/modules/qt_lib_quick3dhelpersimpl_private.pri \
		/usr/mkspecs/modules/qt_lib_quick3diblbaker.pri \
		/usr/mkspecs/modules/qt_lib_quick3diblbaker_private.pri \
		/usr/mkspecs/modules/qt_lib_quick3dparticleeffects.pri \
		/usr/mkspecs/modules/qt_lib_quick3dparticleeffects_private.pri \
		/usr/mkspecs/modules/qt_lib_quick3dparticles.pri \
		/usr/mkspecs/modules/qt_lib_quick3dparticles_private.pri \
		/usr/mkspecs/modules/qt_lib_quick3dphysics.pri \
		/usr/mkspecs/modules/qt_lib_quick3dphysics_private.pri \
		/usr/mkspecs/modules/qt_lib_quick3dphysicshelpers.pri \
		/usr/mkspecs/modules/qt_lib_quick3dphysicshelpers_private.pri \
		/usr/mkspecs/modules/qt_lib_quick3drender.pri \
		/usr/mkspecs/modules/qt_lib_quick3drender_private.pri \
		/usr/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		/usr/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		/usr/mkspecs/modules/qt_lib_quick3dspatialaudio_private.pri \
		/usr/mkspecs/modules/qt_lib_quick3dutils.pri \
		/usr/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		/usr/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		/usr/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		/usr/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		/usr/mkspecs/modules/qt_lib_quickdialogs2.pri \
		/usr/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		/usr/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		/usr/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		/usr/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		/usr/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		/usr/mkspecs/modules/qt_lib_quickeffects_private.pri \
		/usr/mkspecs/modules/qt_lib_quicklayouts.pri \
		/usr/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		/usr/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/usr/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		/usr/mkspecs/modules/qt_lib_quicktimeline.pri \
		/usr/mkspecs/modules/qt_lib_quicktimeline_private.pri \
		/usr/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/mkspecs/modules/qt_lib_remoteobjects.pri \
		/usr/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/usr/mkspecs/modules/qt_lib_remoteobjectsqml.pri \
		/usr/mkspecs/modules/qt_lib_remoteobjectsqml_private.pri \
		/usr/mkspecs/modules/qt_lib_repparser.pri \
		/usr/mkspecs/modules/qt_lib_repparser_private.pri \
		/usr/mkspecs/modules/qt_lib_scxml.pri \
		/usr/mkspecs/modules/qt_lib_scxml_private.pri \
		/usr/mkspecs/modules/qt_lib_scxmlqml.pri \
		/usr/mkspecs/modules/qt_lib_scxmlqml_private.pri \
		/usr/mkspecs/modules/qt_lib_sensors.pri \
		/usr/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/mkspecs/modules/qt_lib_sensorsquick.pri \
		/usr/mkspecs/modules/qt_lib_sensorsquick_private.pri \
		/usr/mkspecs/modules/qt_lib_serialbus.pri \
		/usr/mkspecs/modules/qt_lib_serialbus_private.pri \
		/usr/mkspecs/modules/qt_lib_serialport.pri \
		/usr/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/mkspecs/modules/qt_lib_shadertools.pri \
		/usr/mkspecs/modules/qt_lib_shadertools_private.pri \
		/usr/mkspecs/modules/qt_lib_spatialaudio.pri \
		/usr/mkspecs/modules/qt_lib_spatialaudio_private.pri \
		/usr/mkspecs/modules/qt_lib_sql.pri \
		/usr/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/mkspecs/modules/qt_lib_statemachine.pri \
		/usr/mkspecs/modules/qt_lib_statemachine_private.pri \
		/usr/mkspecs/modules/qt_lib_statemachineqml.pri \
		/usr/mkspecs/modules/qt_lib_statemachineqml_private.pri \
		/usr/mkspecs/modules/qt_lib_svg.pri \
		/usr/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/mkspecs/modules/qt_lib_svgwidgets.pri \
		/usr/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		/usr/mkspecs/modules/qt_lib_testlib.pri \
		/usr/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/mkspecs/modules/qt_lib_texttospeech.pri \
		/usr/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/usr/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/mkspecs/modules/qt_lib_tools_private.pri \
		/usr/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/mkspecs/modules/qt_lib_uitools.pri \
		/usr/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/usr/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/usr/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/mkspecs/modules/qt_lib_wayland_egl_client_hw_integration_private.pri \
		/usr/mkspecs/modules/qt_lib_wayland_egl_compositor_hw_integration_private.pri \
		/usr/mkspecs/modules/qt_lib_waylandclient.pri \
		/usr/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/usr/mkspecs/modules/qt_lib_waylandcompositor.pri \
		/usr/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		/usr/mkspecs/modules/qt_lib_waylandglobal_private.pri \
		/usr/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/mkspecs/modules/qt_lib_websockets.pri \
		/usr/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/mkspecs/modules/qt_lib_webview.pri \
		/usr/mkspecs/modules/qt_lib_webview_private.pri \
		/usr/mkspecs/modules/qt_lib_webviewquick.pri \
		/usr/mkspecs/modules/qt_lib_webviewquick_private.pri \
		/usr/mkspecs/modules/qt_lib_widgets.pri \
		/usr/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/mkspecs/modules/qt_lib_wl_shell_integration_private.pri \
		/usr/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/mkspecs/modules/qt_lib_x11extras_private.pri \
		/usr/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/mkspecs/modules/qt_lib_xml.pri \
		/usr/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/mkspecs/modules/qt_lib_zlib_private.pri \
		/usr/mkspecs/features/qt_functions.prf \
		/usr/mkspecs/features/qt_config.prf \
		/usr/mkspecs/linux-clang/qmake.conf \
		/usr/mkspecs/features/spec_post.prf \
		/usr/mkspecs/features/exclusive_builds.prf \
		/usr/mkspecs/features/toolchain.prf \
		/usr/mkspecs/features/default_pre.prf \
		/usr/mkspecs/features/resolve_config.prf \
		/usr/mkspecs/features/default_post.prf \
		/usr/mkspecs/features/warn_on.prf \
		/usr/mkspecs/features/qt.prf \
		/usr/mkspecs/features/resources_functions.prf \
		/usr/mkspecs/features/resources.prf \
		/usr/mkspecs/features/moc.prf \
		/usr/mkspecs/features/unix/opengl.prf \
		/usr/mkspecs/features/uic.prf \
		/usr/mkspecs/features/unix/thread.prf \
		/usr/mkspecs/features/qmake_use.prf \
		/usr/mkspecs/features/file_copies.prf \
		/usr/mkspecs/features/testcase_targets.prf \
		/usr/mkspecs/features/exceptions.prf \
		/usr/mkspecs/features/yacc.prf \
		/usr/mkspecs/features/lex.prf \
		Xplist.pro mainwindow.h \
		MyTabBar.h \
		MyTabPopup.h \
		Plist.hpp \
		PlistDate.hpp \
		autoupdatedialog.h \
		base64.hpp \
		codeeditor.h \
		comboboxdelegatebool.h \
		domparser.h \
		dommodel.h \
		domitem.h \
		comboboxdelegate.h \
		filesystemwatcher.h \
		lineeditdelegate.h \
		editortab.h \
		editortabswidget.h \
		commands.h \
		itemstate.h \
		myapp.h \
		myhighlighter.h \
		mytreeview.h \
		pugiconfig.hpp \
		pugixml.hpp \
		recentfiles.h main.cpp \
		MyTabBar.cpp \
		MyTabPopup.cpp \
		Plist.cpp \
		PlistDate.cpp \
		autoupdatedialog.cpp \
		codeeditor.cpp \
		comboboxdelegatebool.cpp \
		filesystemwatcher.cpp \
		mainwindow.cpp \
		domparser.cpp \
		dommodel.cpp \
		domitem.cpp \
		comboboxdelegate.cpp \
		lineeditdelegate.cpp \
		editortab.cpp \
		editortabswidget.cpp \
		commands.cpp \
		itemstate.cpp \
		myapp.cpp \
		myhighlighter.cpp \
		mytreeview.cpp \
		pugixml.cpp \
		recentfiles.cpp
QMAKE_TARGET  = Xplist
DESTDIR       = bin/release/
TARGET        = bin/release/Xplist


first: all
####### Build rules

bin/release/Xplist: ui_mainwindow.h ui_autoupdatedialog.h ui_editortab.h $(OBJECTS)  
	@test -d bin/release/ || mkdir -p bin/release/
	$(LINK) $(LFLAGS) -o $(TARGET)  $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Xplist.pro /usr/mkspecs/linux-clang/qmake.conf /usr/mkspecs/features/spec_pre.prf \
		/usr/mkspecs/common/unix.conf \
		/usr/mkspecs/common/linux.conf \
		/usr/mkspecs/common/sanitize.conf \
		/usr/mkspecs/common/gcc-base.conf \
		/usr/mkspecs/common/gcc-base-unix.conf \
		/usr/mkspecs/common/clang.conf \
		/usr/mkspecs/qconfig.pri \
		/usr/mkspecs/modules/qt_lib_3danimation.pri \
		/usr/mkspecs/modules/qt_lib_3danimation_private.pri \
		/usr/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/mkspecs/modules/qt_lib_3dcore_private.pri \
		/usr/mkspecs/modules/qt_lib_3dextras.pri \
		/usr/mkspecs/modules/qt_lib_3dextras_private.pri \
		/usr/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/mkspecs/modules/qt_lib_3dinput_private.pri \
		/usr/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/usr/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/usr/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/usr/mkspecs/modules/qt_lib_3dquickextras.pri \
		/usr/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/usr/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/usr/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/usr/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/usr/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/usr/mkspecs/modules/qt_lib_3drender.pri \
		/usr/mkspecs/modules/qt_lib_3drender_private.pri \
		/usr/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/mkspecs/modules/qt_lib_bodymovin_private.pri \
		/usr/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/mkspecs/modules/qt_lib_charts.pri \
		/usr/mkspecs/modules/qt_lib_charts_private.pri \
		/usr/mkspecs/modules/qt_lib_chartsqml.pri \
		/usr/mkspecs/modules/qt_lib_chartsqml_private.pri \
		/usr/mkspecs/modules/qt_lib_coap.pri \
		/usr/mkspecs/modules/qt_lib_coap_private.pri \
		/usr/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/mkspecs/modules/qt_lib_core.pri \
		/usr/mkspecs/modules/qt_lib_core5compat.pri \
		/usr/mkspecs/modules/qt_lib_core5compat_private.pri \
		/usr/mkspecs/modules/qt_lib_core_private.pri \
		/usr/mkspecs/modules/qt_lib_datavisualization.pri \
		/usr/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/usr/mkspecs/modules/qt_lib_datavisualizationqml.pri \
		/usr/mkspecs/modules/qt_lib_datavisualizationqml_private.pri \
		/usr/mkspecs/modules/qt_lib_dbus.pri \
		/usr/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/mkspecs/modules/qt_lib_declarativeopcua.pri \
		/usr/mkspecs/modules/qt_lib_declarativeopcua_private.pri \
		/usr/mkspecs/modules/qt_lib_designer.pri \
		/usr/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/mkspecs/modules/qt_lib_example_icons_private.pri \
		/usr/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/mkspecs/modules/qt_lib_freetype_private.pri \
		/usr/mkspecs/modules/qt_lib_gamepad.pri \
		/usr/mkspecs/modules/qt_lib_gamepad_private.pri \
		/usr/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/mkspecs/modules/qt_lib_grpc.pri \
		/usr/mkspecs/modules/qt_lib_grpc_private.pri \
		/usr/mkspecs/modules/qt_lib_gui.pri \
		/usr/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/mkspecs/modules/qt_lib_harfbuzz_private.pri \
		/usr/mkspecs/modules/qt_lib_help.pri \
		/usr/mkspecs/modules/qt_lib_help_private.pri \
		/usr/mkspecs/modules/qt_lib_httpserver.pri \
		/usr/mkspecs/modules/qt_lib_httpserver_private.pri \
		/usr/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/mkspecs/modules/qt_lib_jpeg_private.pri \
		/usr/mkspecs/modules/qt_lib_jsonrpc_private.pri \
		/usr/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/mkspecs/modules/qt_lib_labsanimation.pri \
		/usr/mkspecs/modules/qt_lib_labsanimation_private.pri \
		/usr/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		/usr/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		/usr/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		/usr/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		/usr/mkspecs/modules/qt_lib_labssettings.pri \
		/usr/mkspecs/modules/qt_lib_labssettings_private.pri \
		/usr/mkspecs/modules/qt_lib_labssharedimage.pri \
		/usr/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		/usr/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		/usr/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		/usr/mkspecs/modules/qt_lib_languageserver_private.pri \
		/usr/mkspecs/modules/qt_lib_linguist.pri \
		/usr/mkspecs/modules/qt_lib_linguist_private.pri \
		/usr/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/mkspecs/modules/qt_lib_location.pri \
		/usr/mkspecs/modules/qt_lib_location_private.pri \
		/usr/mkspecs/modules/qt_lib_mqtt.pri \
		/usr/mkspecs/modules/qt_lib_mqtt_private.pri \
		/usr/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/mkspecs/modules/qt_lib_multimediaquick_private.pri \
		/usr/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/mkspecs/modules/qt_lib_network.pri \
		/usr/mkspecs/modules/qt_lib_network_private.pri \
		/usr/mkspecs/modules/qt_lib_networkauth.pri \
		/usr/mkspecs/modules/qt_lib_networkauth_private.pri \
		/usr/mkspecs/modules/qt_lib_nfc.pri \
		/usr/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/mkspecs/modules/qt_lib_opcua.pri \
		/usr/mkspecs/modules/qt_lib_opcua_private.pri \
		/usr/mkspecs/modules/qt_lib_opengl.pri \
		/usr/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/mkspecs/modules/qt_lib_openglwidgets.pri \
		/usr/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		/usr/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/mkspecs/modules/qt_lib_png_private.pri \
		/usr/mkspecs/modules/qt_lib_positioning.pri \
		/usr/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/usr/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/mkspecs/modules/qt_lib_protobuf.pri \
		/usr/mkspecs/modules/qt_lib_protobuf_private.pri \
		/usr/mkspecs/modules/qt_lib_purchasing.pri \
		/usr/mkspecs/modules/qt_lib_purchasing_private.pri \
		/usr/mkspecs/modules/qt_lib_qml.pri \
		/usr/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		/usr/mkspecs/modules/qt_lib_qmlcore.pri \
		/usr/mkspecs/modules/qt_lib_qmlcore_private.pri \
		/usr/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/mkspecs/modules/qt_lib_qmldom_private.pri \
		/usr/mkspecs/modules/qt_lib_qmlintegration.pri \
		/usr/mkspecs/modules/qt_lib_qmlintegration_private.pri \
		/usr/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		/usr/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		/usr/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/usr/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri \
		/usr/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/usr/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		/usr/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		/usr/mkspecs/modules/qt_lib_quick.pri \
		/usr/mkspecs/modules/qt_lib_quick3d.pri \
		/usr/mkspecs/modules/qt_lib_quick3d_private.pri \
		/usr/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		/usr/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		/usr/mkspecs/modules/qt_lib_quick3dassetutils.pri \
		/usr/mkspecs/modules/qt_lib_quick3dassetutils_private.pri \
		/usr/mkspecs/modules/qt_lib_quick3deffects.pri \
		/usr/mkspecs/modules/qt_lib_quick3deffects_private.pri \
		/usr/mkspecs/modules/qt_lib_quick3dglslparser_private.pri \
		/usr/mkspecs/modules/qt_lib_quick3dhelpers.pri \
		/usr/mkspecs/modules/qt_lib_quick3dhelpers_private.pri \
		/usr/mkspecs/modules/qt_lib_quick3dhelpersimpl.pri \
		/usr/mkspecs/modules/qt_lib_quick3dhelpersimpl_private.pri \
		/usr/mkspecs/modules/qt_lib_quick3diblbaker.pri \
		/usr/mkspecs/modules/qt_lib_quick3diblbaker_private.pri \
		/usr/mkspecs/modules/qt_lib_quick3dparticleeffects.pri \
		/usr/mkspecs/modules/qt_lib_quick3dparticleeffects_private.pri \
		/usr/mkspecs/modules/qt_lib_quick3dparticles.pri \
		/usr/mkspecs/modules/qt_lib_quick3dparticles_private.pri \
		/usr/mkspecs/modules/qt_lib_quick3dphysics.pri \
		/usr/mkspecs/modules/qt_lib_quick3dphysics_private.pri \
		/usr/mkspecs/modules/qt_lib_quick3dphysicshelpers.pri \
		/usr/mkspecs/modules/qt_lib_quick3dphysicshelpers_private.pri \
		/usr/mkspecs/modules/qt_lib_quick3drender.pri \
		/usr/mkspecs/modules/qt_lib_quick3drender_private.pri \
		/usr/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		/usr/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		/usr/mkspecs/modules/qt_lib_quick3dspatialaudio_private.pri \
		/usr/mkspecs/modules/qt_lib_quick3dutils.pri \
		/usr/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		/usr/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		/usr/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		/usr/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		/usr/mkspecs/modules/qt_lib_quickdialogs2.pri \
		/usr/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		/usr/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		/usr/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		/usr/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		/usr/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		/usr/mkspecs/modules/qt_lib_quickeffects_private.pri \
		/usr/mkspecs/modules/qt_lib_quicklayouts.pri \
		/usr/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		/usr/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/usr/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		/usr/mkspecs/modules/qt_lib_quicktimeline.pri \
		/usr/mkspecs/modules/qt_lib_quicktimeline_private.pri \
		/usr/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/mkspecs/modules/qt_lib_remoteobjects.pri \
		/usr/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/usr/mkspecs/modules/qt_lib_remoteobjectsqml.pri \
		/usr/mkspecs/modules/qt_lib_remoteobjectsqml_private.pri \
		/usr/mkspecs/modules/qt_lib_repparser.pri \
		/usr/mkspecs/modules/qt_lib_repparser_private.pri \
		/usr/mkspecs/modules/qt_lib_scxml.pri \
		/usr/mkspecs/modules/qt_lib_scxml_private.pri \
		/usr/mkspecs/modules/qt_lib_scxmlqml.pri \
		/usr/mkspecs/modules/qt_lib_scxmlqml_private.pri \
		/usr/mkspecs/modules/qt_lib_sensors.pri \
		/usr/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/mkspecs/modules/qt_lib_sensorsquick.pri \
		/usr/mkspecs/modules/qt_lib_sensorsquick_private.pri \
		/usr/mkspecs/modules/qt_lib_serialbus.pri \
		/usr/mkspecs/modules/qt_lib_serialbus_private.pri \
		/usr/mkspecs/modules/qt_lib_serialport.pri \
		/usr/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/mkspecs/modules/qt_lib_shadertools.pri \
		/usr/mkspecs/modules/qt_lib_shadertools_private.pri \
		/usr/mkspecs/modules/qt_lib_spatialaudio.pri \
		/usr/mkspecs/modules/qt_lib_spatialaudio_private.pri \
		/usr/mkspecs/modules/qt_lib_sql.pri \
		/usr/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/mkspecs/modules/qt_lib_statemachine.pri \
		/usr/mkspecs/modules/qt_lib_statemachine_private.pri \
		/usr/mkspecs/modules/qt_lib_statemachineqml.pri \
		/usr/mkspecs/modules/qt_lib_statemachineqml_private.pri \
		/usr/mkspecs/modules/qt_lib_svg.pri \
		/usr/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/mkspecs/modules/qt_lib_svgwidgets.pri \
		/usr/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		/usr/mkspecs/modules/qt_lib_testlib.pri \
		/usr/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/mkspecs/modules/qt_lib_texttospeech.pri \
		/usr/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/usr/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/mkspecs/modules/qt_lib_tools_private.pri \
		/usr/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/mkspecs/modules/qt_lib_uitools.pri \
		/usr/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/usr/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/usr/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/mkspecs/modules/qt_lib_wayland_egl_client_hw_integration_private.pri \
		/usr/mkspecs/modules/qt_lib_wayland_egl_compositor_hw_integration_private.pri \
		/usr/mkspecs/modules/qt_lib_waylandclient.pri \
		/usr/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/usr/mkspecs/modules/qt_lib_waylandcompositor.pri \
		/usr/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		/usr/mkspecs/modules/qt_lib_waylandglobal_private.pri \
		/usr/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/mkspecs/modules/qt_lib_websockets.pri \
		/usr/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/mkspecs/modules/qt_lib_webview.pri \
		/usr/mkspecs/modules/qt_lib_webview_private.pri \
		/usr/mkspecs/modules/qt_lib_webviewquick.pri \
		/usr/mkspecs/modules/qt_lib_webviewquick_private.pri \
		/usr/mkspecs/modules/qt_lib_widgets.pri \
		/usr/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/mkspecs/modules/qt_lib_wl_shell_integration_private.pri \
		/usr/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/mkspecs/modules/qt_lib_x11extras_private.pri \
		/usr/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/mkspecs/modules/qt_lib_xml.pri \
		/usr/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/mkspecs/modules/qt_lib_zlib_private.pri \
		/usr/mkspecs/features/qt_functions.prf \
		/usr/mkspecs/features/qt_config.prf \
		/usr/mkspecs/linux-clang/qmake.conf \
		/usr/mkspecs/features/spec_post.prf \
		/usr/mkspecs/features/exclusive_builds.prf \
		/usr/mkspecs/features/toolchain.prf \
		/usr/mkspecs/features/default_pre.prf \
		/usr/mkspecs/features/resolve_config.prf \
		/usr/mkspecs/features/default_post.prf \
		/usr/mkspecs/features/warn_on.prf \
		/usr/mkspecs/features/qt.prf \
		/usr/mkspecs/features/resources_functions.prf \
		/usr/mkspecs/features/resources.prf \
		/usr/mkspecs/features/moc.prf \
		/usr/mkspecs/features/unix/opengl.prf \
		/usr/mkspecs/features/uic.prf \
		/usr/mkspecs/features/unix/thread.prf \
		/usr/mkspecs/features/qmake_use.prf \
		/usr/mkspecs/features/file_copies.prf \
		/usr/mkspecs/features/testcase_targets.prf \
		/usr/mkspecs/features/exceptions.prf \
		/usr/mkspecs/features/yacc.prf \
		/usr/mkspecs/features/lex.prf \
		Xplist.pro \
		res.qrc \
		/usr/lib/libQt6Widgets.prl \
		/usr/lib/libQt6Gui.prl \
		/usr/lib/libQt6Xml.prl \
		/usr/lib/libQt6Network.prl \
		/usr/lib/libQt6Core.prl
	$(QMAKE) -o Makefile Xplist.pro
/usr/mkspecs/features/spec_pre.prf:
/usr/mkspecs/common/unix.conf:
/usr/mkspecs/common/linux.conf:
/usr/mkspecs/common/sanitize.conf:
/usr/mkspecs/common/gcc-base.conf:
/usr/mkspecs/common/gcc-base-unix.conf:
/usr/mkspecs/common/clang.conf:
/usr/mkspecs/qconfig.pri:
/usr/mkspecs/modules/qt_lib_3danimation.pri:
/usr/mkspecs/modules/qt_lib_3danimation_private.pri:
/usr/mkspecs/modules/qt_lib_3dcore.pri:
/usr/mkspecs/modules/qt_lib_3dcore_private.pri:
/usr/mkspecs/modules/qt_lib_3dextras.pri:
/usr/mkspecs/modules/qt_lib_3dextras_private.pri:
/usr/mkspecs/modules/qt_lib_3dinput.pri:
/usr/mkspecs/modules/qt_lib_3dinput_private.pri:
/usr/mkspecs/modules/qt_lib_3dlogic.pri:
/usr/mkspecs/modules/qt_lib_3dlogic_private.pri:
/usr/mkspecs/modules/qt_lib_3dquick.pri:
/usr/mkspecs/modules/qt_lib_3dquick_private.pri:
/usr/mkspecs/modules/qt_lib_3dquickanimation.pri:
/usr/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/usr/mkspecs/modules/qt_lib_3dquickextras.pri:
/usr/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/usr/mkspecs/modules/qt_lib_3dquickinput.pri:
/usr/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/usr/mkspecs/modules/qt_lib_3dquickrender.pri:
/usr/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/usr/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/usr/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/usr/mkspecs/modules/qt_lib_3drender.pri:
/usr/mkspecs/modules/qt_lib_3drender_private.pri:
/usr/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/mkspecs/modules/qt_lib_bluetooth.pri:
/usr/mkspecs/modules/qt_lib_bluetooth_private.pri:
/usr/mkspecs/modules/qt_lib_bodymovin_private.pri:
/usr/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/mkspecs/modules/qt_lib_charts.pri:
/usr/mkspecs/modules/qt_lib_charts_private.pri:
/usr/mkspecs/modules/qt_lib_chartsqml.pri:
/usr/mkspecs/modules/qt_lib_chartsqml_private.pri:
/usr/mkspecs/modules/qt_lib_coap.pri:
/usr/mkspecs/modules/qt_lib_coap_private.pri:
/usr/mkspecs/modules/qt_lib_concurrent.pri:
/usr/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/mkspecs/modules/qt_lib_core.pri:
/usr/mkspecs/modules/qt_lib_core5compat.pri:
/usr/mkspecs/modules/qt_lib_core5compat_private.pri:
/usr/mkspecs/modules/qt_lib_core_private.pri:
/usr/mkspecs/modules/qt_lib_datavisualization.pri:
/usr/mkspecs/modules/qt_lib_datavisualization_private.pri:
/usr/mkspecs/modules/qt_lib_datavisualizationqml.pri:
/usr/mkspecs/modules/qt_lib_datavisualizationqml_private.pri:
/usr/mkspecs/modules/qt_lib_dbus.pri:
/usr/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/mkspecs/modules/qt_lib_declarativeopcua.pri:
/usr/mkspecs/modules/qt_lib_declarativeopcua_private.pri:
/usr/mkspecs/modules/qt_lib_designer.pri:
/usr/mkspecs/modules/qt_lib_designer_private.pri:
/usr/mkspecs/modules/qt_lib_designercomponents_private.pri:
/usr/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/mkspecs/modules/qt_lib_example_icons_private.pri:
/usr/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/mkspecs/modules/qt_lib_freetype_private.pri:
/usr/mkspecs/modules/qt_lib_gamepad.pri:
/usr/mkspecs/modules/qt_lib_gamepad_private.pri:
/usr/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/mkspecs/modules/qt_lib_grpc.pri:
/usr/mkspecs/modules/qt_lib_grpc_private.pri:
/usr/mkspecs/modules/qt_lib_gui.pri:
/usr/mkspecs/modules/qt_lib_gui_private.pri:
/usr/mkspecs/modules/qt_lib_harfbuzz_private.pri:
/usr/mkspecs/modules/qt_lib_help.pri:
/usr/mkspecs/modules/qt_lib_help_private.pri:
/usr/mkspecs/modules/qt_lib_httpserver.pri:
/usr/mkspecs/modules/qt_lib_httpserver_private.pri:
/usr/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/mkspecs/modules/qt_lib_jpeg_private.pri:
/usr/mkspecs/modules/qt_lib_jsonrpc_private.pri:
/usr/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/mkspecs/modules/qt_lib_labsanimation.pri:
/usr/mkspecs/modules/qt_lib_labsanimation_private.pri:
/usr/mkspecs/modules/qt_lib_labsfolderlistmodel.pri:
/usr/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri:
/usr/mkspecs/modules/qt_lib_labsqmlmodels.pri:
/usr/mkspecs/modules/qt_lib_labsqmlmodels_private.pri:
/usr/mkspecs/modules/qt_lib_labssettings.pri:
/usr/mkspecs/modules/qt_lib_labssettings_private.pri:
/usr/mkspecs/modules/qt_lib_labssharedimage.pri:
/usr/mkspecs/modules/qt_lib_labssharedimage_private.pri:
/usr/mkspecs/modules/qt_lib_labswavefrontmesh.pri:
/usr/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri:
/usr/mkspecs/modules/qt_lib_languageserver_private.pri:
/usr/mkspecs/modules/qt_lib_linguist.pri:
/usr/mkspecs/modules/qt_lib_linguist_private.pri:
/usr/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/mkspecs/modules/qt_lib_location.pri:
/usr/mkspecs/modules/qt_lib_location_private.pri:
/usr/mkspecs/modules/qt_lib_mqtt.pri:
/usr/mkspecs/modules/qt_lib_mqtt_private.pri:
/usr/mkspecs/modules/qt_lib_multimedia.pri:
/usr/mkspecs/modules/qt_lib_multimedia_private.pri:
/usr/mkspecs/modules/qt_lib_multimediaquick_private.pri:
/usr/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/usr/mkspecs/modules/qt_lib_network.pri:
/usr/mkspecs/modules/qt_lib_network_private.pri:
/usr/mkspecs/modules/qt_lib_networkauth.pri:
/usr/mkspecs/modules/qt_lib_networkauth_private.pri:
/usr/mkspecs/modules/qt_lib_nfc.pri:
/usr/mkspecs/modules/qt_lib_nfc_private.pri:
/usr/mkspecs/modules/qt_lib_opcua.pri:
/usr/mkspecs/modules/qt_lib_opcua_private.pri:
/usr/mkspecs/modules/qt_lib_opengl.pri:
/usr/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/mkspecs/modules/qt_lib_openglwidgets.pri:
/usr/mkspecs/modules/qt_lib_openglwidgets_private.pri:
/usr/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/usr/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/mkspecs/modules/qt_lib_png_private.pri:
/usr/mkspecs/modules/qt_lib_positioning.pri:
/usr/mkspecs/modules/qt_lib_positioning_private.pri:
/usr/mkspecs/modules/qt_lib_positioningquick.pri:
/usr/mkspecs/modules/qt_lib_positioningquick_private.pri:
/usr/mkspecs/modules/qt_lib_printsupport.pri:
/usr/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/mkspecs/modules/qt_lib_protobuf.pri:
/usr/mkspecs/modules/qt_lib_protobuf_private.pri:
/usr/mkspecs/modules/qt_lib_purchasing.pri:
/usr/mkspecs/modules/qt_lib_purchasing_private.pri:
/usr/mkspecs/modules/qt_lib_qml.pri:
/usr/mkspecs/modules/qt_lib_qml_private.pri:
/usr/mkspecs/modules/qt_lib_qmlcompiler_private.pri:
/usr/mkspecs/modules/qt_lib_qmlcore.pri:
/usr/mkspecs/modules/qt_lib_qmlcore_private.pri:
/usr/mkspecs/modules/qt_lib_qmldebug_private.pri:
/usr/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/usr/mkspecs/modules/qt_lib_qmldom_private.pri:
/usr/mkspecs/modules/qt_lib_qmlintegration.pri:
/usr/mkspecs/modules/qt_lib_qmlintegration_private.pri:
/usr/mkspecs/modules/qt_lib_qmllocalstorage.pri:
/usr/mkspecs/modules/qt_lib_qmllocalstorage_private.pri:
/usr/mkspecs/modules/qt_lib_qmlmodels.pri:
/usr/mkspecs/modules/qt_lib_qmlmodels_private.pri:
/usr/mkspecs/modules/qt_lib_qmltest.pri:
/usr/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri:
/usr/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/usr/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
/usr/mkspecs/modules/qt_lib_qmlxmllistmodel.pri:
/usr/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri:
/usr/mkspecs/modules/qt_lib_quick.pri:
/usr/mkspecs/modules/qt_lib_quick3d.pri:
/usr/mkspecs/modules/qt_lib_quick3d_private.pri:
/usr/mkspecs/modules/qt_lib_quick3dassetimport.pri:
/usr/mkspecs/modules/qt_lib_quick3dassetimport_private.pri:
/usr/mkspecs/modules/qt_lib_quick3dassetutils.pri:
/usr/mkspecs/modules/qt_lib_quick3dassetutils_private.pri:
/usr/mkspecs/modules/qt_lib_quick3deffects.pri:
/usr/mkspecs/modules/qt_lib_quick3deffects_private.pri:
/usr/mkspecs/modules/qt_lib_quick3dglslparser_private.pri:
/usr/mkspecs/modules/qt_lib_quick3dhelpers.pri:
/usr/mkspecs/modules/qt_lib_quick3dhelpers_private.pri:
/usr/mkspecs/modules/qt_lib_quick3dhelpersimpl.pri:
/usr/mkspecs/modules/qt_lib_quick3dhelpersimpl_private.pri:
/usr/mkspecs/modules/qt_lib_quick3diblbaker.pri:
/usr/mkspecs/modules/qt_lib_quick3diblbaker_private.pri:
/usr/mkspecs/modules/qt_lib_quick3dparticleeffects.pri:
/usr/mkspecs/modules/qt_lib_quick3dparticleeffects_private.pri:
/usr/mkspecs/modules/qt_lib_quick3dparticles.pri:
/usr/mkspecs/modules/qt_lib_quick3dparticles_private.pri:
/usr/mkspecs/modules/qt_lib_quick3dphysics.pri:
/usr/mkspecs/modules/qt_lib_quick3dphysics_private.pri:
/usr/mkspecs/modules/qt_lib_quick3dphysicshelpers.pri:
/usr/mkspecs/modules/qt_lib_quick3dphysicshelpers_private.pri:
/usr/mkspecs/modules/qt_lib_quick3drender.pri:
/usr/mkspecs/modules/qt_lib_quick3drender_private.pri:
/usr/mkspecs/modules/qt_lib_quick3druntimerender.pri:
/usr/mkspecs/modules/qt_lib_quick3druntimerender_private.pri:
/usr/mkspecs/modules/qt_lib_quick3dspatialaudio_private.pri:
/usr/mkspecs/modules/qt_lib_quick3dutils.pri:
/usr/mkspecs/modules/qt_lib_quick3dutils_private.pri:
/usr/mkspecs/modules/qt_lib_quick_private.pri:
/usr/mkspecs/modules/qt_lib_quickcontrols2.pri:
/usr/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/usr/mkspecs/modules/qt_lib_quickcontrols2impl.pri:
/usr/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri:
/usr/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri:
/usr/mkspecs/modules/qt_lib_quickdialogs2.pri:
/usr/mkspecs/modules/qt_lib_quickdialogs2_private.pri:
/usr/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri:
/usr/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri:
/usr/mkspecs/modules/qt_lib_quickdialogs2utils.pri:
/usr/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri:
/usr/mkspecs/modules/qt_lib_quickeffects_private.pri:
/usr/mkspecs/modules/qt_lib_quicklayouts.pri:
/usr/mkspecs/modules/qt_lib_quicklayouts_private.pri:
/usr/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/mkspecs/modules/qt_lib_quickshapes_private.pri:
/usr/mkspecs/modules/qt_lib_quicktemplates2.pri:
/usr/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/usr/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri:
/usr/mkspecs/modules/qt_lib_quicktimeline.pri:
/usr/mkspecs/modules/qt_lib_quicktimeline_private.pri:
/usr/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/mkspecs/modules/qt_lib_remoteobjects.pri:
/usr/mkspecs/modules/qt_lib_remoteobjects_private.pri:
/usr/mkspecs/modules/qt_lib_remoteobjectsqml.pri:
/usr/mkspecs/modules/qt_lib_remoteobjectsqml_private.pri:
/usr/mkspecs/modules/qt_lib_repparser.pri:
/usr/mkspecs/modules/qt_lib_repparser_private.pri:
/usr/mkspecs/modules/qt_lib_scxml.pri:
/usr/mkspecs/modules/qt_lib_scxml_private.pri:
/usr/mkspecs/modules/qt_lib_scxmlqml.pri:
/usr/mkspecs/modules/qt_lib_scxmlqml_private.pri:
/usr/mkspecs/modules/qt_lib_sensors.pri:
/usr/mkspecs/modules/qt_lib_sensors_private.pri:
/usr/mkspecs/modules/qt_lib_sensorsquick.pri:
/usr/mkspecs/modules/qt_lib_sensorsquick_private.pri:
/usr/mkspecs/modules/qt_lib_serialbus.pri:
/usr/mkspecs/modules/qt_lib_serialbus_private.pri:
/usr/mkspecs/modules/qt_lib_serialport.pri:
/usr/mkspecs/modules/qt_lib_serialport_private.pri:
/usr/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/mkspecs/modules/qt_lib_shadertools.pri:
/usr/mkspecs/modules/qt_lib_shadertools_private.pri:
/usr/mkspecs/modules/qt_lib_spatialaudio.pri:
/usr/mkspecs/modules/qt_lib_spatialaudio_private.pri:
/usr/mkspecs/modules/qt_lib_sql.pri:
/usr/mkspecs/modules/qt_lib_sql_private.pri:
/usr/mkspecs/modules/qt_lib_statemachine.pri:
/usr/mkspecs/modules/qt_lib_statemachine_private.pri:
/usr/mkspecs/modules/qt_lib_statemachineqml.pri:
/usr/mkspecs/modules/qt_lib_statemachineqml_private.pri:
/usr/mkspecs/modules/qt_lib_svg.pri:
/usr/mkspecs/modules/qt_lib_svg_private.pri:
/usr/mkspecs/modules/qt_lib_svgwidgets.pri:
/usr/mkspecs/modules/qt_lib_svgwidgets_private.pri:
/usr/mkspecs/modules/qt_lib_testlib.pri:
/usr/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/mkspecs/modules/qt_lib_texttospeech.pri:
/usr/mkspecs/modules/qt_lib_texttospeech_private.pri:
/usr/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/mkspecs/modules/qt_lib_tools_private.pri:
/usr/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/mkspecs/modules/qt_lib_uitools.pri:
/usr/mkspecs/modules/qt_lib_uitools_private.pri:
/usr/mkspecs/modules/qt_lib_virtualkeyboard.pri:
/usr/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
/usr/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/mkspecs/modules/qt_lib_wayland_egl_client_hw_integration_private.pri:
/usr/mkspecs/modules/qt_lib_wayland_egl_compositor_hw_integration_private.pri:
/usr/mkspecs/modules/qt_lib_waylandclient.pri:
/usr/mkspecs/modules/qt_lib_waylandclient_private.pri:
/usr/mkspecs/modules/qt_lib_waylandcompositor.pri:
/usr/mkspecs/modules/qt_lib_waylandcompositor_private.pri:
/usr/mkspecs/modules/qt_lib_waylandglobal_private.pri:
/usr/mkspecs/modules/qt_lib_webchannel.pri:
/usr/mkspecs/modules/qt_lib_webchannel_private.pri:
/usr/mkspecs/modules/qt_lib_websockets.pri:
/usr/mkspecs/modules/qt_lib_websockets_private.pri:
/usr/mkspecs/modules/qt_lib_webview.pri:
/usr/mkspecs/modules/qt_lib_webview_private.pri:
/usr/mkspecs/modules/qt_lib_webviewquick.pri:
/usr/mkspecs/modules/qt_lib_webviewquick_private.pri:
/usr/mkspecs/modules/qt_lib_widgets.pri:
/usr/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/mkspecs/modules/qt_lib_wl_shell_integration_private.pri:
/usr/mkspecs/modules/qt_lib_x11extras.pri:
/usr/mkspecs/modules/qt_lib_x11extras_private.pri:
/usr/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
/usr/mkspecs/modules/qt_lib_xml.pri:
/usr/mkspecs/modules/qt_lib_xml_private.pri:
/usr/mkspecs/modules/qt_lib_zlib_private.pri:
/usr/mkspecs/features/qt_functions.prf:
/usr/mkspecs/features/qt_config.prf:
/usr/mkspecs/linux-clang/qmake.conf:
/usr/mkspecs/features/spec_post.prf:
/usr/mkspecs/features/exclusive_builds.prf:
/usr/mkspecs/features/toolchain.prf:
/usr/mkspecs/features/default_pre.prf:
/usr/mkspecs/features/resolve_config.prf:
/usr/mkspecs/features/default_post.prf:
/usr/mkspecs/features/warn_on.prf:
/usr/mkspecs/features/qt.prf:
/usr/mkspecs/features/resources_functions.prf:
/usr/mkspecs/features/resources.prf:
/usr/mkspecs/features/moc.prf:
/usr/mkspecs/features/unix/opengl.prf:
/usr/mkspecs/features/uic.prf:
/usr/mkspecs/features/unix/thread.prf:
/usr/mkspecs/features/qmake_use.prf:
/usr/mkspecs/features/file_copies.prf:
/usr/mkspecs/features/testcase_targets.prf:
/usr/mkspecs/features/exceptions.prf:
/usr/mkspecs/features/yacc.prf:
/usr/mkspecs/features/lex.prf:
Xplist.pro:
res.qrc:
/usr/lib/libQt6Widgets.prl:
/usr/lib/libQt6Gui.prl:
/usr/lib/libQt6Xml.prl:
/usr/lib/libQt6Network.prl:
/usr/lib/libQt6Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile Xplist.pro

qmake_all: FORCE


all: Makefile bin/release/Xplist

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents res.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /usr/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.h MyTabBar.h MyTabPopup.h Plist.hpp PlistDate.hpp autoupdatedialog.h base64.hpp codeeditor.h comboboxdelegatebool.h domparser.h dommodel.h domitem.h comboboxdelegate.h filesystemwatcher.h lineeditdelegate.h editortab.h editortabswidget.h commands.h itemstate.h myapp.h myhighlighter.h mytreeview.h pugiconfig.hpp pugixml.hpp recentfiles.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp MyTabBar.cpp MyTabPopup.cpp Plist.cpp PlistDate.cpp autoupdatedialog.cpp codeeditor.cpp comboboxdelegatebool.cpp filesystemwatcher.cpp mainwindow.cpp domparser.cpp dommodel.cpp domitem.cpp comboboxdelegate.cpp lineeditdelegate.cpp editortab.cpp editortabswidget.cpp commands.cpp itemstate.cpp myapp.cpp myhighlighter.cpp mytreeview.cpp pugixml.cpp recentfiles.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui autoupdatedialog.ui editortab.ui $(DISTDIR)/
	$(COPY_FILE) --parents translation_ru.ts translation_cn.ts $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_res.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_res.cpp
qrc_res.cpp: res.qrc \
		/usr/libexec/rcc \
		res/col.svg \
		res/down.svg \
		res/my.png \
		res/undo.svg \
		res/new.png \
		res/child.svg \
		res/redo.svg \
		res/translation_cn.qm \
		res/rp.svg \
		res/new.svg \
		res/up.svg \
		res/c0.png \
		res/translation_ru.qm \
		res/widgets_zh_cn.qm \
		res/saveas.svg \
		res/exp.svg \
		res/pre.svg \
		res/save.png \
		res/open.svg \
		res/find.png \
		res/cu.svg \
		res/next.svg \
		res/qt_zh_CN.qm \
		res/sibling.svg \
		res/sort.svg \
		res/replace.svg \
		res/child.png \
		res/find.svg \
		res/main.svg \
		res/nw.svg \
		res/sub.svg \
		res/sibling.png \
		res/del.png \
		res/c.png \
		res/red.svg \
		res/remove.svg \
		res/green.svg \
		res/save.svg
	/usr/libexec/rcc -name res res.qrc -o qrc_res.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/mkspecs/features/data/dummy.cpp
	clang++ -pipe -O2 -std=gnu++1z -Wall -Wextra -fPIC -dM -E -o moc_predefs.h /usr/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp moc_MyTabBar.cpp moc_MyTabPopup.cpp moc_autoupdatedialog.cpp moc_codeeditor.cpp moc_comboboxdelegatebool.cpp moc_dommodel.cpp moc_comboboxdelegate.cpp moc_filesystemwatcher.cpp moc_lineeditdelegate.cpp moc_editortab.cpp moc_editortabswidget.cpp moc_myhighlighter.cpp moc_mytreeview.cpp moc_recentfiles.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_MyTabBar.cpp moc_MyTabPopup.cpp moc_autoupdatedialog.cpp moc_codeeditor.cpp moc_comboboxdelegatebool.cpp moc_dommodel.cpp moc_comboboxdelegate.cpp moc_filesystemwatcher.cpp moc_lineeditdelegate.cpp moc_editortab.cpp moc_editortabswidget.cpp moc_myhighlighter.cpp moc_mytreeview.cpp moc_recentfiles.cpp
moc_mainwindow.cpp: mainwindow.h \
		autoupdatedialog.h \
		codeeditor.h \
		domparser.h \
		dommodel.h \
		domitem.h \
		itemstate.h \
		editortabswidget.h \
		editortab.h \
		comboboxdelegate.h \
		comboboxdelegatebool.h \
		commands.h \
		lineeditdelegate.h \
		mytreeview.h \
		myhighlighter.h \
		recentfiles.h \
		moc_predefs.h \
		/usr/libexec/moc
	/usr/libexec/moc $(DEFINES) --include /home/andyvand/Downloads/Xplist/moc_predefs.h -I/usr/mkspecs/linux-clang -I/home/andyvand/Downloads/Xplist -I/usr/include/QtWidgets -I/usr/include/QtGui -I/usr/include/QtXml -I/usr/include/QtNetwork -I/usr/include/QtCore -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/llvm-15/lib/clang/15.0.7/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include mainwindow.h -o moc_mainwindow.cpp

moc_MyTabBar.cpp: MyTabBar.h \
		moc_predefs.h \
		/usr/libexec/moc
	/usr/libexec/moc $(DEFINES) --include /home/andyvand/Downloads/Xplist/moc_predefs.h -I/usr/mkspecs/linux-clang -I/home/andyvand/Downloads/Xplist -I/usr/include/QtWidgets -I/usr/include/QtGui -I/usr/include/QtXml -I/usr/include/QtNetwork -I/usr/include/QtCore -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/llvm-15/lib/clang/15.0.7/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include MyTabBar.h -o moc_MyTabBar.cpp

moc_MyTabPopup.cpp: MyTabPopup.h \
		moc_predefs.h \
		/usr/libexec/moc
	/usr/libexec/moc $(DEFINES) --include /home/andyvand/Downloads/Xplist/moc_predefs.h -I/usr/mkspecs/linux-clang -I/home/andyvand/Downloads/Xplist -I/usr/include/QtWidgets -I/usr/include/QtGui -I/usr/include/QtXml -I/usr/include/QtNetwork -I/usr/include/QtCore -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/llvm-15/lib/clang/15.0.7/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include MyTabPopup.h -o moc_MyTabPopup.cpp

moc_autoupdatedialog.cpp: autoupdatedialog.h \
		moc_predefs.h \
		/usr/libexec/moc
	/usr/libexec/moc $(DEFINES) --include /home/andyvand/Downloads/Xplist/moc_predefs.h -I/usr/mkspecs/linux-clang -I/home/andyvand/Downloads/Xplist -I/usr/include/QtWidgets -I/usr/include/QtGui -I/usr/include/QtXml -I/usr/include/QtNetwork -I/usr/include/QtCore -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/llvm-15/lib/clang/15.0.7/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include autoupdatedialog.h -o moc_autoupdatedialog.cpp

moc_codeeditor.cpp: codeeditor.h \
		moc_predefs.h \
		/usr/libexec/moc
	/usr/libexec/moc $(DEFINES) --include /home/andyvand/Downloads/Xplist/moc_predefs.h -I/usr/mkspecs/linux-clang -I/home/andyvand/Downloads/Xplist -I/usr/include/QtWidgets -I/usr/include/QtGui -I/usr/include/QtXml -I/usr/include/QtNetwork -I/usr/include/QtCore -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/llvm-15/lib/clang/15.0.7/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include codeeditor.h -o moc_codeeditor.cpp

moc_comboboxdelegatebool.cpp: comboboxdelegatebool.h \
		moc_predefs.h \
		/usr/libexec/moc
	/usr/libexec/moc $(DEFINES) --include /home/andyvand/Downloads/Xplist/moc_predefs.h -I/usr/mkspecs/linux-clang -I/home/andyvand/Downloads/Xplist -I/usr/include/QtWidgets -I/usr/include/QtGui -I/usr/include/QtXml -I/usr/include/QtNetwork -I/usr/include/QtCore -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/llvm-15/lib/clang/15.0.7/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include comboboxdelegatebool.h -o moc_comboboxdelegatebool.cpp

moc_dommodel.cpp: dommodel.h \
		domitem.h \
		itemstate.h \
		dommodel.h \
		moc_predefs.h \
		/usr/libexec/moc
	/usr/libexec/moc $(DEFINES) --include /home/andyvand/Downloads/Xplist/moc_predefs.h -I/usr/mkspecs/linux-clang -I/home/andyvand/Downloads/Xplist -I/usr/include/QtWidgets -I/usr/include/QtGui -I/usr/include/QtXml -I/usr/include/QtNetwork -I/usr/include/QtCore -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/llvm-15/lib/clang/15.0.7/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include dommodel.h -o moc_dommodel.cpp

moc_comboboxdelegate.cpp: comboboxdelegate.h \
		domitem.h \
		dommodel.h \
		itemstate.h \
		moc_predefs.h \
		/usr/libexec/moc
	/usr/libexec/moc $(DEFINES) --include /home/andyvand/Downloads/Xplist/moc_predefs.h -I/usr/mkspecs/linux-clang -I/home/andyvand/Downloads/Xplist -I/usr/include/QtWidgets -I/usr/include/QtGui -I/usr/include/QtXml -I/usr/include/QtNetwork -I/usr/include/QtCore -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/llvm-15/lib/clang/15.0.7/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include comboboxdelegate.h -o moc_comboboxdelegate.cpp

moc_filesystemwatcher.cpp: filesystemwatcher.h \
		moc_predefs.h \
		/usr/libexec/moc
	/usr/libexec/moc $(DEFINES) --include /home/andyvand/Downloads/Xplist/moc_predefs.h -I/usr/mkspecs/linux-clang -I/home/andyvand/Downloads/Xplist -I/usr/include/QtWidgets -I/usr/include/QtGui -I/usr/include/QtXml -I/usr/include/QtNetwork -I/usr/include/QtCore -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/llvm-15/lib/clang/15.0.7/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include filesystemwatcher.h -o moc_filesystemwatcher.cpp

moc_lineeditdelegate.cpp: lineeditdelegate.h \
		moc_predefs.h \
		/usr/libexec/moc
	/usr/libexec/moc $(DEFINES) --include /home/andyvand/Downloads/Xplist/moc_predefs.h -I/usr/mkspecs/linux-clang -I/home/andyvand/Downloads/Xplist -I/usr/include/QtWidgets -I/usr/include/QtGui -I/usr/include/QtXml -I/usr/include/QtNetwork -I/usr/include/QtCore -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/llvm-15/lib/clang/15.0.7/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include lineeditdelegate.h -o moc_lineeditdelegate.cpp

moc_editortab.cpp: editortab.h \
		comboboxdelegate.h \
		domitem.h \
		dommodel.h \
		itemstate.h \
		comboboxdelegatebool.h \
		commands.h \
		lineeditdelegate.h \
		mytreeview.h \
		moc_predefs.h \
		/usr/libexec/moc
	/usr/libexec/moc $(DEFINES) --include /home/andyvand/Downloads/Xplist/moc_predefs.h -I/usr/mkspecs/linux-clang -I/home/andyvand/Downloads/Xplist -I/usr/include/QtWidgets -I/usr/include/QtGui -I/usr/include/QtXml -I/usr/include/QtNetwork -I/usr/include/QtCore -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/llvm-15/lib/clang/15.0.7/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include editortab.h -o moc_editortab.cpp

moc_editortabswidget.cpp: editortabswidget.h \
		editortab.h \
		comboboxdelegate.h \
		domitem.h \
		dommodel.h \
		itemstate.h \
		comboboxdelegatebool.h \
		commands.h \
		lineeditdelegate.h \
		mytreeview.h \
		moc_predefs.h \
		/usr/libexec/moc
	/usr/libexec/moc $(DEFINES) --include /home/andyvand/Downloads/Xplist/moc_predefs.h -I/usr/mkspecs/linux-clang -I/home/andyvand/Downloads/Xplist -I/usr/include/QtWidgets -I/usr/include/QtGui -I/usr/include/QtXml -I/usr/include/QtNetwork -I/usr/include/QtCore -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/llvm-15/lib/clang/15.0.7/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include editortabswidget.h -o moc_editortabswidget.cpp

moc_myhighlighter.cpp: myhighlighter.h \
		moc_predefs.h \
		/usr/libexec/moc
	/usr/libexec/moc $(DEFINES) --include /home/andyvand/Downloads/Xplist/moc_predefs.h -I/usr/mkspecs/linux-clang -I/home/andyvand/Downloads/Xplist -I/usr/include/QtWidgets -I/usr/include/QtGui -I/usr/include/QtXml -I/usr/include/QtNetwork -I/usr/include/QtCore -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/llvm-15/lib/clang/15.0.7/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include myhighlighter.h -o moc_myhighlighter.cpp

moc_mytreeview.cpp: mytreeview.h \
		moc_predefs.h \
		/usr/libexec/moc
	/usr/libexec/moc $(DEFINES) --include /home/andyvand/Downloads/Xplist/moc_predefs.h -I/usr/mkspecs/linux-clang -I/home/andyvand/Downloads/Xplist -I/usr/include/QtWidgets -I/usr/include/QtGui -I/usr/include/QtXml -I/usr/include/QtNetwork -I/usr/include/QtCore -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/llvm-15/lib/clang/15.0.7/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include mytreeview.h -o moc_mytreeview.cpp

moc_recentfiles.cpp: recentfiles.h \
		moc_predefs.h \
		/usr/libexec/moc
	/usr/libexec/moc $(DEFINES) --include /home/andyvand/Downloads/Xplist/moc_predefs.h -I/usr/mkspecs/linux-clang -I/home/andyvand/Downloads/Xplist -I/usr/include/QtWidgets -I/usr/include/QtGui -I/usr/include/QtXml -I/usr/include/QtNetwork -I/usr/include/QtCore -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/llvm-15/lib/clang/15.0.7/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include recentfiles.h -o moc_recentfiles.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_autoupdatedialog.h ui_editortab.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_autoupdatedialog.h ui_editortab.h
ui_mainwindow.h: mainwindow.ui \
		/usr/libexec/uic
	/usr/libexec/uic mainwindow.ui -o ui_mainwindow.h

ui_autoupdatedialog.h: autoupdatedialog.ui \
		/usr/libexec/uic
	/usr/libexec/uic autoupdatedialog.ui -o ui_autoupdatedialog.h

ui_editortab.h: editortab.ui \
		/usr/libexec/uic
	/usr/libexec/uic editortab.ui -o ui_editortab.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		autoupdatedialog.h \
		codeeditor.h \
		domparser.h \
		dommodel.h \
		domitem.h \
		itemstate.h \
		editortabswidget.h \
		editortab.h \
		comboboxdelegate.h \
		comboboxdelegatebool.h \
		commands.h \
		lineeditdelegate.h \
		mytreeview.h \
		myhighlighter.h \
		recentfiles.h \
		myapp.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

MyTabBar.o: MyTabBar.cpp MyTabBar.h \
		editortabswidget.h \
		editortab.h \
		comboboxdelegate.h \
		domitem.h \
		dommodel.h \
		itemstate.h \
		comboboxdelegatebool.h \
		commands.h \
		lineeditdelegate.h \
		mytreeview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MyTabBar.o MyTabBar.cpp

MyTabPopup.o: MyTabPopup.cpp MyTabPopup.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MyTabPopup.o MyTabPopup.cpp

Plist.o: Plist.cpp Plist.hpp \
		boost/any.hpp \
		boost/config.hpp \
		boost/config/select_compiler_config.hpp \
		boost/config/compiler/nvcc.hpp \
		boost/config/select_stdlib_config.hpp \
		boost/config/no_tr1/utility.hpp \
		boost/config/select_platform_config.hpp \
		boost/config/posix_features.hpp \
		boost/config/suffix.hpp \
		boost/type_traits/remove_reference.hpp \
		boost/type_traits/broken_compiler_spec.hpp \
		boost/mpl/aux_/lambda_support.hpp \
		boost/mpl/aux_/config/lambda.hpp \
		boost/mpl/aux_/config/ttp.hpp \
		boost/mpl/aux_/config/msvc.hpp \
		boost/mpl/aux_/config/gcc.hpp \
		boost/mpl/aux_/config/workaround.hpp \
		boost/detail/workaround.hpp \
		boost/mpl/aux_/config/ctps.hpp \
		boost/mpl/int_fwd.hpp \
		boost/mpl/aux_/adl_barrier.hpp \
		boost/mpl/aux_/config/adl.hpp \
		boost/mpl/aux_/config/intel.hpp \
		boost/mpl/aux_/nttp_decl.hpp \
		boost/mpl/aux_/config/nttp.hpp \
		boost/preprocessor/cat.hpp \
		boost/preprocessor/config/config.hpp \
		boost/mpl/aux_/yes_no.hpp \
		boost/mpl/aux_/config/arrays.hpp \
		boost/mpl/aux_/na_fwd.hpp \
		boost/mpl/aux_/preprocessor/params.hpp \
		boost/mpl/aux_/config/preprocessor.hpp \
		boost/preprocessor/comma_if.hpp \
		boost/preprocessor/punctuation/comma_if.hpp \
		boost/preprocessor/control/if.hpp \
		boost/preprocessor/control/iif.hpp \
		boost/preprocessor/logical/bool.hpp \
		boost/preprocessor/facilities/empty.hpp \
		boost/preprocessor/punctuation/comma.hpp \
		boost/preprocessor/repeat.hpp \
		boost/preprocessor/repetition/repeat.hpp \
		boost/preprocessor/debug/error.hpp \
		boost/preprocessor/detail/auto_rec.hpp \
		boost/preprocessor/detail/dmc/auto_rec.hpp \
		boost/preprocessor/tuple/eat.hpp \
		boost/preprocessor/inc.hpp \
		boost/preprocessor/arithmetic/inc.hpp \
		boost/mpl/aux_/preprocessor/enum.hpp \
		boost/preprocessor/tuple/to_list.hpp \
		boost/preprocessor/facilities/overload.hpp \
		boost/preprocessor/variadic/size.hpp \
		boost/preprocessor/list/for_each_i.hpp \
		boost/preprocessor/list/adt.hpp \
		boost/preprocessor/detail/is_binary.hpp \
		boost/preprocessor/detail/check.hpp \
		boost/preprocessor/logical/compl.hpp \
		boost/preprocessor/repetition/for.hpp \
		boost/preprocessor/repetition/detail/edg/for.hpp \
		boost/preprocessor/repetition/detail/msvc/for.hpp \
		boost/preprocessor/repetition/detail/dmc/for.hpp \
		boost/preprocessor/control/expr_iif.hpp \
		boost/preprocessor/repetition/detail/for.hpp \
		boost/preprocessor/tuple/elem.hpp \
		boost/preprocessor/tuple/rem.hpp \
		boost/preprocessor/variadic/elem.hpp \
		boost/type_traits/detail/type_trait_undef.hpp \
		boost/type_traits/msvc/remove_reference.hpp \
		boost/type_traits/msvc/typeof.hpp \
		boost/type_traits/is_reference.hpp \
		boost/type_traits/config.hpp \
		boost/type_traits/is_lvalue_reference.hpp \
		boost/type_traits/detail/yes_no_type.hpp \
		boost/type_traits/detail/wrap.hpp \
		boost/type_traits/detail/bool_trait_def.hpp \
		boost/type_traits/detail/template_arity_spec.hpp \
		boost/mpl/int.hpp \
		boost/mpl/aux_/integral_wrapper.hpp \
		boost/mpl/integral_c_tag.hpp \
		boost/mpl/aux_/config/static_constant.hpp \
		boost/mpl/aux_/static_cast.hpp \
		boost/mpl/aux_/template_arity_fwd.hpp \
		boost/mpl/aux_/config/overload_resolution.hpp \
		boost/type_traits/integral_constant.hpp \
		boost/mpl/bool.hpp \
		boost/mpl/bool_fwd.hpp \
		boost/mpl/integral_c.hpp \
		boost/mpl/integral_c_fwd.hpp \
		boost/type_traits/detail/bool_trait_undef.hpp \
		boost/type_traits/is_rvalue_reference.hpp \
		boost/type_traits/ice.hpp \
		boost/type_traits/detail/ice_or.hpp \
		boost/type_traits/detail/ice_and.hpp \
		boost/type_traits/detail/ice_not.hpp \
		boost/type_traits/detail/ice_eq.hpp \
		boost/type_traits/detail/type_trait_def.hpp \
		boost/type_traits/decay.hpp \
		boost/type_traits/is_array.hpp \
		boost/type_traits/is_function.hpp \
		boost/type_traits/detail/false_result.hpp \
		boost/type_traits/detail/is_function_ptr_helper.hpp \
		boost/preprocessor/iterate.hpp \
		boost/preprocessor/iteration/iterate.hpp \
		boost/preprocessor/arithmetic/dec.hpp \
		boost/preprocessor/array/elem.hpp \
		boost/preprocessor/array/data.hpp \
		boost/preprocessor/array/size.hpp \
		boost/preprocessor/slot/slot.hpp \
		boost/preprocessor/slot/detail/def.hpp \
		boost/preprocessor/enum_params.hpp \
		boost/preprocessor/repetition/enum_params.hpp \
		boost/type_traits/detail/is_function_ptr_tester.hpp \
		boost/type_traits/remove_bounds.hpp \
		boost/type_traits/msvc/remove_bounds.hpp \
		boost/type_traits/add_pointer.hpp \
		boost/mpl/eval_if.hpp \
		boost/mpl/if.hpp \
		boost/mpl/aux_/value_wknd.hpp \
		boost/mpl/aux_/config/integral.hpp \
		boost/mpl/aux_/config/eti.hpp \
		boost/mpl/aux_/na_spec.hpp \
		boost/mpl/lambda_fwd.hpp \
		boost/mpl/void_fwd.hpp \
		boost/mpl/aux_/na.hpp \
		boost/mpl/aux_/lambda_arity_param.hpp \
		boost/mpl/aux_/arity.hpp \
		boost/mpl/aux_/config/dtp.hpp \
		boost/mpl/aux_/preprocessor/def_params_tail.hpp \
		boost/mpl/limits/arity.hpp \
		boost/preprocessor/logical/and.hpp \
		boost/preprocessor/logical/bitand.hpp \
		boost/preprocessor/identity.hpp \
		boost/preprocessor/facilities/identity.hpp \
		boost/preprocessor/empty.hpp \
		boost/mpl/aux_/preprocessor/filter_params.hpp \
		boost/mpl/aux_/preprocessor/sub.hpp \
		boost/mpl/aux_/preprocessor/tuple.hpp \
		boost/preprocessor/arithmetic/sub.hpp \
		boost/preprocessor/control/while.hpp \
		boost/preprocessor/list/fold_left.hpp \
		boost/preprocessor/list/detail/edg/fold_left.hpp \
		boost/preprocessor/list/detail/dmc/fold_left.hpp \
		boost/preprocessor/list/detail/fold_left.hpp \
		boost/preprocessor/list/fold_right.hpp \
		boost/preprocessor/list/detail/edg/fold_right.hpp \
		boost/preprocessor/list/detail/fold_right.hpp \
		boost/preprocessor/list/reverse.hpp \
		boost/preprocessor/control/detail/edg/while.hpp \
		boost/preprocessor/control/detail/msvc/while.hpp \
		boost/preprocessor/control/detail/dmc/while.hpp \
		boost/preprocessor/control/detail/while.hpp \
		boost/preprocessor/arithmetic/add.hpp \
		boost/mpl/identity.hpp \
		boost/type_traits/add_reference.hpp \
		boost/type_traits/is_const.hpp \
		boost/type_traits/detail/cv_traits_impl.hpp \
		boost/throw_exception.hpp \
		boost/exception/detail/attribute_noreturn.hpp \
		boost/exception/exception.hpp \
		boost/current_function.hpp \
		boost/static_assert.hpp \
		boost/utility/enable_if.hpp \
		boost/type_traits/is_same.hpp \
		boost/cstdint.hpp \
		boost/limits.hpp \
		PlistDate.hpp \
		boost/locale/encoding_utf.hpp \
		boost/locale/utf.hpp \
		boost/locale/encoding_errors.hpp \
		boost/locale/definitions.hpp \
		base64.hpp \
		pugixml.hpp \
		pugiconfig.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Plist.o Plist.cpp

PlistDate.o: PlistDate.cpp PlistDate.hpp \
		Plist.hpp \
		boost/any.hpp \
		boost/config.hpp \
		boost/config/select_compiler_config.hpp \
		boost/config/compiler/nvcc.hpp \
		boost/config/select_stdlib_config.hpp \
		boost/config/no_tr1/utility.hpp \
		boost/config/select_platform_config.hpp \
		boost/config/posix_features.hpp \
		boost/config/suffix.hpp \
		boost/type_traits/remove_reference.hpp \
		boost/type_traits/broken_compiler_spec.hpp \
		boost/mpl/aux_/lambda_support.hpp \
		boost/mpl/aux_/config/lambda.hpp \
		boost/mpl/aux_/config/ttp.hpp \
		boost/mpl/aux_/config/msvc.hpp \
		boost/mpl/aux_/config/gcc.hpp \
		boost/mpl/aux_/config/workaround.hpp \
		boost/detail/workaround.hpp \
		boost/mpl/aux_/config/ctps.hpp \
		boost/mpl/int_fwd.hpp \
		boost/mpl/aux_/adl_barrier.hpp \
		boost/mpl/aux_/config/adl.hpp \
		boost/mpl/aux_/config/intel.hpp \
		boost/mpl/aux_/nttp_decl.hpp \
		boost/mpl/aux_/config/nttp.hpp \
		boost/preprocessor/cat.hpp \
		boost/preprocessor/config/config.hpp \
		boost/mpl/aux_/yes_no.hpp \
		boost/mpl/aux_/config/arrays.hpp \
		boost/mpl/aux_/na_fwd.hpp \
		boost/mpl/aux_/preprocessor/params.hpp \
		boost/mpl/aux_/config/preprocessor.hpp \
		boost/preprocessor/comma_if.hpp \
		boost/preprocessor/punctuation/comma_if.hpp \
		boost/preprocessor/control/if.hpp \
		boost/preprocessor/control/iif.hpp \
		boost/preprocessor/logical/bool.hpp \
		boost/preprocessor/facilities/empty.hpp \
		boost/preprocessor/punctuation/comma.hpp \
		boost/preprocessor/repeat.hpp \
		boost/preprocessor/repetition/repeat.hpp \
		boost/preprocessor/debug/error.hpp \
		boost/preprocessor/detail/auto_rec.hpp \
		boost/preprocessor/detail/dmc/auto_rec.hpp \
		boost/preprocessor/tuple/eat.hpp \
		boost/preprocessor/inc.hpp \
		boost/preprocessor/arithmetic/inc.hpp \
		boost/mpl/aux_/preprocessor/enum.hpp \
		boost/preprocessor/tuple/to_list.hpp \
		boost/preprocessor/facilities/overload.hpp \
		boost/preprocessor/variadic/size.hpp \
		boost/preprocessor/list/for_each_i.hpp \
		boost/preprocessor/list/adt.hpp \
		boost/preprocessor/detail/is_binary.hpp \
		boost/preprocessor/detail/check.hpp \
		boost/preprocessor/logical/compl.hpp \
		boost/preprocessor/repetition/for.hpp \
		boost/preprocessor/repetition/detail/edg/for.hpp \
		boost/preprocessor/repetition/detail/msvc/for.hpp \
		boost/preprocessor/repetition/detail/dmc/for.hpp \
		boost/preprocessor/control/expr_iif.hpp \
		boost/preprocessor/repetition/detail/for.hpp \
		boost/preprocessor/tuple/elem.hpp \
		boost/preprocessor/tuple/rem.hpp \
		boost/preprocessor/variadic/elem.hpp \
		boost/type_traits/detail/type_trait_undef.hpp \
		boost/type_traits/msvc/remove_reference.hpp \
		boost/type_traits/msvc/typeof.hpp \
		boost/type_traits/is_reference.hpp \
		boost/type_traits/config.hpp \
		boost/type_traits/is_lvalue_reference.hpp \
		boost/type_traits/detail/yes_no_type.hpp \
		boost/type_traits/detail/wrap.hpp \
		boost/type_traits/detail/bool_trait_def.hpp \
		boost/type_traits/detail/template_arity_spec.hpp \
		boost/mpl/int.hpp \
		boost/mpl/aux_/integral_wrapper.hpp \
		boost/mpl/integral_c_tag.hpp \
		boost/mpl/aux_/config/static_constant.hpp \
		boost/mpl/aux_/static_cast.hpp \
		boost/mpl/aux_/template_arity_fwd.hpp \
		boost/mpl/aux_/config/overload_resolution.hpp \
		boost/type_traits/integral_constant.hpp \
		boost/mpl/bool.hpp \
		boost/mpl/bool_fwd.hpp \
		boost/mpl/integral_c.hpp \
		boost/mpl/integral_c_fwd.hpp \
		boost/type_traits/detail/bool_trait_undef.hpp \
		boost/type_traits/is_rvalue_reference.hpp \
		boost/type_traits/ice.hpp \
		boost/type_traits/detail/ice_or.hpp \
		boost/type_traits/detail/ice_and.hpp \
		boost/type_traits/detail/ice_not.hpp \
		boost/type_traits/detail/ice_eq.hpp \
		boost/type_traits/detail/type_trait_def.hpp \
		boost/type_traits/decay.hpp \
		boost/type_traits/is_array.hpp \
		boost/type_traits/is_function.hpp \
		boost/type_traits/detail/false_result.hpp \
		boost/type_traits/detail/is_function_ptr_helper.hpp \
		boost/preprocessor/iterate.hpp \
		boost/preprocessor/iteration/iterate.hpp \
		boost/preprocessor/arithmetic/dec.hpp \
		boost/preprocessor/array/elem.hpp \
		boost/preprocessor/array/data.hpp \
		boost/preprocessor/array/size.hpp \
		boost/preprocessor/slot/slot.hpp \
		boost/preprocessor/slot/detail/def.hpp \
		boost/preprocessor/enum_params.hpp \
		boost/preprocessor/repetition/enum_params.hpp \
		boost/type_traits/detail/is_function_ptr_tester.hpp \
		boost/type_traits/remove_bounds.hpp \
		boost/type_traits/msvc/remove_bounds.hpp \
		boost/type_traits/add_pointer.hpp \
		boost/mpl/eval_if.hpp \
		boost/mpl/if.hpp \
		boost/mpl/aux_/value_wknd.hpp \
		boost/mpl/aux_/config/integral.hpp \
		boost/mpl/aux_/config/eti.hpp \
		boost/mpl/aux_/na_spec.hpp \
		boost/mpl/lambda_fwd.hpp \
		boost/mpl/void_fwd.hpp \
		boost/mpl/aux_/na.hpp \
		boost/mpl/aux_/lambda_arity_param.hpp \
		boost/mpl/aux_/arity.hpp \
		boost/mpl/aux_/config/dtp.hpp \
		boost/mpl/aux_/preprocessor/def_params_tail.hpp \
		boost/mpl/limits/arity.hpp \
		boost/preprocessor/logical/and.hpp \
		boost/preprocessor/logical/bitand.hpp \
		boost/preprocessor/identity.hpp \
		boost/preprocessor/facilities/identity.hpp \
		boost/preprocessor/empty.hpp \
		boost/mpl/aux_/preprocessor/filter_params.hpp \
		boost/mpl/aux_/preprocessor/sub.hpp \
		boost/mpl/aux_/preprocessor/tuple.hpp \
		boost/preprocessor/arithmetic/sub.hpp \
		boost/preprocessor/control/while.hpp \
		boost/preprocessor/list/fold_left.hpp \
		boost/preprocessor/list/detail/edg/fold_left.hpp \
		boost/preprocessor/list/detail/dmc/fold_left.hpp \
		boost/preprocessor/list/detail/fold_left.hpp \
		boost/preprocessor/list/fold_right.hpp \
		boost/preprocessor/list/detail/edg/fold_right.hpp \
		boost/preprocessor/list/detail/fold_right.hpp \
		boost/preprocessor/list/reverse.hpp \
		boost/preprocessor/control/detail/edg/while.hpp \
		boost/preprocessor/control/detail/msvc/while.hpp \
		boost/preprocessor/control/detail/dmc/while.hpp \
		boost/preprocessor/control/detail/while.hpp \
		boost/preprocessor/arithmetic/add.hpp \
		boost/mpl/identity.hpp \
		boost/type_traits/add_reference.hpp \
		boost/type_traits/is_const.hpp \
		boost/type_traits/detail/cv_traits_impl.hpp \
		boost/throw_exception.hpp \
		boost/exception/detail/attribute_noreturn.hpp \
		boost/exception/exception.hpp \
		boost/current_function.hpp \
		boost/static_assert.hpp \
		boost/utility/enable_if.hpp \
		boost/type_traits/is_same.hpp \
		boost/cstdint.hpp \
		boost/limits.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o PlistDate.o PlistDate.cpp

autoupdatedialog.o: autoupdatedialog.cpp autoupdatedialog.h \
		mainwindow.h \
		codeeditor.h \
		domparser.h \
		dommodel.h \
		domitem.h \
		itemstate.h \
		editortabswidget.h \
		editortab.h \
		comboboxdelegate.h \
		comboboxdelegatebool.h \
		commands.h \
		lineeditdelegate.h \
		mytreeview.h \
		myhighlighter.h \
		recentfiles.h \
		ui_autoupdatedialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o autoupdatedialog.o autoupdatedialog.cpp

codeeditor.o: codeeditor.cpp codeeditor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o codeeditor.o codeeditor.cpp

comboboxdelegatebool.o: comboboxdelegatebool.cpp comboboxdelegatebool.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o comboboxdelegatebool.o comboboxdelegatebool.cpp

filesystemwatcher.o: filesystemwatcher.cpp filesystemwatcher.h \
		mainwindow.h \
		autoupdatedialog.h \
		codeeditor.h \
		domparser.h \
		dommodel.h \
		domitem.h \
		itemstate.h \
		editortabswidget.h \
		editortab.h \
		comboboxdelegate.h \
		comboboxdelegatebool.h \
		commands.h \
		lineeditdelegate.h \
		mytreeview.h \
		myhighlighter.h \
		recentfiles.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o filesystemwatcher.o filesystemwatcher.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		autoupdatedialog.h \
		codeeditor.h \
		domparser.h \
		dommodel.h \
		domitem.h \
		itemstate.h \
		editortabswidget.h \
		editortab.h \
		comboboxdelegate.h \
		comboboxdelegatebool.h \
		commands.h \
		lineeditdelegate.h \
		mytreeview.h \
		myhighlighter.h \
		recentfiles.h \
		Plist.hpp \
		boost/any.hpp \
		boost/config.hpp \
		boost/config/select_compiler_config.hpp \
		boost/config/compiler/nvcc.hpp \
		boost/config/select_stdlib_config.hpp \
		boost/config/no_tr1/utility.hpp \
		boost/config/select_platform_config.hpp \
		boost/config/posix_features.hpp \
		boost/config/suffix.hpp \
		boost/type_traits/remove_reference.hpp \
		boost/type_traits/broken_compiler_spec.hpp \
		boost/mpl/aux_/lambda_support.hpp \
		boost/mpl/aux_/config/lambda.hpp \
		boost/mpl/aux_/config/ttp.hpp \
		boost/mpl/aux_/config/msvc.hpp \
		boost/mpl/aux_/config/gcc.hpp \
		boost/mpl/aux_/config/workaround.hpp \
		boost/detail/workaround.hpp \
		boost/mpl/aux_/config/ctps.hpp \
		boost/mpl/int_fwd.hpp \
		boost/mpl/aux_/adl_barrier.hpp \
		boost/mpl/aux_/config/adl.hpp \
		boost/mpl/aux_/config/intel.hpp \
		boost/mpl/aux_/nttp_decl.hpp \
		boost/mpl/aux_/config/nttp.hpp \
		boost/preprocessor/cat.hpp \
		boost/preprocessor/config/config.hpp \
		boost/mpl/aux_/yes_no.hpp \
		boost/mpl/aux_/config/arrays.hpp \
		boost/mpl/aux_/na_fwd.hpp \
		boost/mpl/aux_/preprocessor/params.hpp \
		boost/mpl/aux_/config/preprocessor.hpp \
		boost/preprocessor/comma_if.hpp \
		boost/preprocessor/punctuation/comma_if.hpp \
		boost/preprocessor/control/if.hpp \
		boost/preprocessor/control/iif.hpp \
		boost/preprocessor/logical/bool.hpp \
		boost/preprocessor/facilities/empty.hpp \
		boost/preprocessor/punctuation/comma.hpp \
		boost/preprocessor/repeat.hpp \
		boost/preprocessor/repetition/repeat.hpp \
		boost/preprocessor/debug/error.hpp \
		boost/preprocessor/detail/auto_rec.hpp \
		boost/preprocessor/detail/dmc/auto_rec.hpp \
		boost/preprocessor/tuple/eat.hpp \
		boost/preprocessor/inc.hpp \
		boost/preprocessor/arithmetic/inc.hpp \
		boost/mpl/aux_/preprocessor/enum.hpp \
		boost/preprocessor/tuple/to_list.hpp \
		boost/preprocessor/facilities/overload.hpp \
		boost/preprocessor/variadic/size.hpp \
		boost/preprocessor/list/for_each_i.hpp \
		boost/preprocessor/list/adt.hpp \
		boost/preprocessor/detail/is_binary.hpp \
		boost/preprocessor/detail/check.hpp \
		boost/preprocessor/logical/compl.hpp \
		boost/preprocessor/repetition/for.hpp \
		boost/preprocessor/repetition/detail/edg/for.hpp \
		boost/preprocessor/repetition/detail/msvc/for.hpp \
		boost/preprocessor/repetition/detail/dmc/for.hpp \
		boost/preprocessor/control/expr_iif.hpp \
		boost/preprocessor/repetition/detail/for.hpp \
		boost/preprocessor/tuple/elem.hpp \
		boost/preprocessor/tuple/rem.hpp \
		boost/preprocessor/variadic/elem.hpp \
		boost/type_traits/detail/type_trait_undef.hpp \
		boost/type_traits/msvc/remove_reference.hpp \
		boost/type_traits/msvc/typeof.hpp \
		boost/type_traits/is_reference.hpp \
		boost/type_traits/config.hpp \
		boost/type_traits/is_lvalue_reference.hpp \
		boost/type_traits/detail/yes_no_type.hpp \
		boost/type_traits/detail/wrap.hpp \
		boost/type_traits/detail/bool_trait_def.hpp \
		boost/type_traits/detail/template_arity_spec.hpp \
		boost/mpl/int.hpp \
		boost/mpl/aux_/integral_wrapper.hpp \
		boost/mpl/integral_c_tag.hpp \
		boost/mpl/aux_/config/static_constant.hpp \
		boost/mpl/aux_/static_cast.hpp \
		boost/mpl/aux_/template_arity_fwd.hpp \
		boost/mpl/aux_/config/overload_resolution.hpp \
		boost/type_traits/integral_constant.hpp \
		boost/mpl/bool.hpp \
		boost/mpl/bool_fwd.hpp \
		boost/mpl/integral_c.hpp \
		boost/mpl/integral_c_fwd.hpp \
		boost/type_traits/detail/bool_trait_undef.hpp \
		boost/type_traits/is_rvalue_reference.hpp \
		boost/type_traits/ice.hpp \
		boost/type_traits/detail/ice_or.hpp \
		boost/type_traits/detail/ice_and.hpp \
		boost/type_traits/detail/ice_not.hpp \
		boost/type_traits/detail/ice_eq.hpp \
		boost/type_traits/detail/type_trait_def.hpp \
		boost/type_traits/decay.hpp \
		boost/type_traits/is_array.hpp \
		boost/type_traits/is_function.hpp \
		boost/type_traits/detail/false_result.hpp \
		boost/type_traits/detail/is_function_ptr_helper.hpp \
		boost/preprocessor/iterate.hpp \
		boost/preprocessor/iteration/iterate.hpp \
		boost/preprocessor/arithmetic/dec.hpp \
		boost/preprocessor/array/elem.hpp \
		boost/preprocessor/array/data.hpp \
		boost/preprocessor/array/size.hpp \
		boost/preprocessor/slot/slot.hpp \
		boost/preprocessor/slot/detail/def.hpp \
		boost/preprocessor/enum_params.hpp \
		boost/preprocessor/repetition/enum_params.hpp \
		boost/type_traits/detail/is_function_ptr_tester.hpp \
		boost/type_traits/remove_bounds.hpp \
		boost/type_traits/msvc/remove_bounds.hpp \
		boost/type_traits/add_pointer.hpp \
		boost/mpl/eval_if.hpp \
		boost/mpl/if.hpp \
		boost/mpl/aux_/value_wknd.hpp \
		boost/mpl/aux_/config/integral.hpp \
		boost/mpl/aux_/config/eti.hpp \
		boost/mpl/aux_/na_spec.hpp \
		boost/mpl/lambda_fwd.hpp \
		boost/mpl/void_fwd.hpp \
		boost/mpl/aux_/na.hpp \
		boost/mpl/aux_/lambda_arity_param.hpp \
		boost/mpl/aux_/arity.hpp \
		boost/mpl/aux_/config/dtp.hpp \
		boost/mpl/aux_/preprocessor/def_params_tail.hpp \
		boost/mpl/limits/arity.hpp \
		boost/preprocessor/logical/and.hpp \
		boost/preprocessor/logical/bitand.hpp \
		boost/preprocessor/identity.hpp \
		boost/preprocessor/facilities/identity.hpp \
		boost/preprocessor/empty.hpp \
		boost/mpl/aux_/preprocessor/filter_params.hpp \
		boost/mpl/aux_/preprocessor/sub.hpp \
		boost/mpl/aux_/preprocessor/tuple.hpp \
		boost/preprocessor/arithmetic/sub.hpp \
		boost/preprocessor/control/while.hpp \
		boost/preprocessor/list/fold_left.hpp \
		boost/preprocessor/list/detail/edg/fold_left.hpp \
		boost/preprocessor/list/detail/dmc/fold_left.hpp \
		boost/preprocessor/list/detail/fold_left.hpp \
		boost/preprocessor/list/fold_right.hpp \
		boost/preprocessor/list/detail/edg/fold_right.hpp \
		boost/preprocessor/list/detail/fold_right.hpp \
		boost/preprocessor/list/reverse.hpp \
		boost/preprocessor/control/detail/edg/while.hpp \
		boost/preprocessor/control/detail/msvc/while.hpp \
		boost/preprocessor/control/detail/dmc/while.hpp \
		boost/preprocessor/control/detail/while.hpp \
		boost/preprocessor/arithmetic/add.hpp \
		boost/mpl/identity.hpp \
		boost/type_traits/add_reference.hpp \
		boost/type_traits/is_const.hpp \
		boost/type_traits/detail/cv_traits_impl.hpp \
		boost/throw_exception.hpp \
		boost/exception/detail/attribute_noreturn.hpp \
		boost/exception/exception.hpp \
		boost/current_function.hpp \
		boost/static_assert.hpp \
		boost/utility/enable_if.hpp \
		boost/type_traits/is_same.hpp \
		boost/cstdint.hpp \
		boost/limits.hpp \
		PlistDate.hpp \
		filesystemwatcher.h \
		myapp.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

domparser.o: domparser.cpp domparser.h \
		dommodel.h \
		domitem.h \
		itemstate.h \
		mainwindow.h \
		autoupdatedialog.h \
		codeeditor.h \
		editortabswidget.h \
		editortab.h \
		comboboxdelegate.h \
		comboboxdelegatebool.h \
		commands.h \
		lineeditdelegate.h \
		mytreeview.h \
		myhighlighter.h \
		recentfiles.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o domparser.o domparser.cpp

dommodel.o: dommodel.cpp dommodel.h \
		domitem.h \
		itemstate.h \
		editortab.h \
		comboboxdelegate.h \
		comboboxdelegatebool.h \
		commands.h \
		lineeditdelegate.h \
		mytreeview.h \
		editortabswidget.h \
		mainwindow.h \
		autoupdatedialog.h \
		codeeditor.h \
		domparser.h \
		myhighlighter.h \
		recentfiles.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dommodel.o dommodel.cpp

domitem.o: domitem.cpp domitem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o domitem.o domitem.cpp

comboboxdelegate.o: comboboxdelegate.cpp comboboxdelegate.h \
		domitem.h \
		dommodel.h \
		itemstate.h \
		editortabswidget.h \
		editortab.h \
		comboboxdelegatebool.h \
		commands.h \
		lineeditdelegate.h \
		mytreeview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o comboboxdelegate.o comboboxdelegate.cpp

lineeditdelegate.o: lineeditdelegate.cpp lineeditdelegate.h \
		domitem.h \
		dommodel.h \
		itemstate.h \
		editortab.h \
		comboboxdelegate.h \
		comboboxdelegatebool.h \
		commands.h \
		mytreeview.h \
		editortabswidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o lineeditdelegate.o lineeditdelegate.cpp

editortab.o: editortab.cpp editortab.h \
		comboboxdelegate.h \
		domitem.h \
		dommodel.h \
		itemstate.h \
		comboboxdelegatebool.h \
		commands.h \
		lineeditdelegate.h \
		mytreeview.h \
		mainwindow.h \
		autoupdatedialog.h \
		codeeditor.h \
		domparser.h \
		editortabswidget.h \
		myhighlighter.h \
		recentfiles.h \
		ui_editortab.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o editortab.o editortab.cpp

editortabswidget.o: editortabswidget.cpp editortabswidget.h \
		editortab.h \
		comboboxdelegate.h \
		domitem.h \
		dommodel.h \
		itemstate.h \
		comboboxdelegatebool.h \
		commands.h \
		lineeditdelegate.h \
		mytreeview.h \
		MyTabBar.h \
		MyTabPopup.h \
		filesystemwatcher.h \
		mainwindow.h \
		autoupdatedialog.h \
		codeeditor.h \
		domparser.h \
		myhighlighter.h \
		recentfiles.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o editortabswidget.o editortabswidget.cpp

commands.o: commands.cpp commands.h \
		dommodel.h \
		domitem.h \
		itemstate.h \
		editortab.h \
		comboboxdelegate.h \
		comboboxdelegatebool.h \
		lineeditdelegate.h \
		mytreeview.h \
		mainwindow.h \
		autoupdatedialog.h \
		codeeditor.h \
		domparser.h \
		editortabswidget.h \
		myhighlighter.h \
		recentfiles.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o commands.o commands.cpp

itemstate.o: itemstate.cpp itemstate.h \
		dommodel.h \
		domitem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o itemstate.o itemstate.cpp

myapp.o: myapp.cpp myapp.h \
		mainwindow.h \
		autoupdatedialog.h \
		codeeditor.h \
		domparser.h \
		dommodel.h \
		domitem.h \
		itemstate.h \
		editortabswidget.h \
		editortab.h \
		comboboxdelegate.h \
		comboboxdelegatebool.h \
		commands.h \
		lineeditdelegate.h \
		mytreeview.h \
		myhighlighter.h \
		recentfiles.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o myapp.o myapp.cpp

myhighlighter.o: myhighlighter.cpp myhighlighter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o myhighlighter.o myhighlighter.cpp

mytreeview.o: mytreeview.cpp mytreeview.h \
		editortabswidget.h \
		editortab.h \
		comboboxdelegate.h \
		domitem.h \
		dommodel.h \
		itemstate.h \
		comboboxdelegatebool.h \
		commands.h \
		lineeditdelegate.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mytreeview.o mytreeview.cpp

pugixml.o: pugixml.cpp pugixml.hpp \
		pugiconfig.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pugixml.o pugixml.cpp

recentfiles.o: recentfiles.cpp recentfiles.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o recentfiles.o recentfiles.cpp

qrc_res.o: qrc_res.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_res.o qrc_res.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_MyTabBar.o: moc_MyTabBar.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MyTabBar.o moc_MyTabBar.cpp

moc_MyTabPopup.o: moc_MyTabPopup.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MyTabPopup.o moc_MyTabPopup.cpp

moc_autoupdatedialog.o: moc_autoupdatedialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_autoupdatedialog.o moc_autoupdatedialog.cpp

moc_codeeditor.o: moc_codeeditor.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_codeeditor.o moc_codeeditor.cpp

moc_comboboxdelegatebool.o: moc_comboboxdelegatebool.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_comboboxdelegatebool.o moc_comboboxdelegatebool.cpp

moc_dommodel.o: moc_dommodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dommodel.o moc_dommodel.cpp

moc_comboboxdelegate.o: moc_comboboxdelegate.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_comboboxdelegate.o moc_comboboxdelegate.cpp

moc_filesystemwatcher.o: moc_filesystemwatcher.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_filesystemwatcher.o moc_filesystemwatcher.cpp

moc_lineeditdelegate.o: moc_lineeditdelegate.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_lineeditdelegate.o moc_lineeditdelegate.cpp

moc_editortab.o: moc_editortab.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_editortab.o moc_editortab.cpp

moc_editortabswidget.o: moc_editortabswidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_editortabswidget.o moc_editortabswidget.cpp

moc_myhighlighter.o: moc_myhighlighter.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_myhighlighter.o moc_myhighlighter.cpp

moc_mytreeview.o: moc_mytreeview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mytreeview.o moc_mytreeview.cpp

moc_recentfiles.o: moc_recentfiles.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_recentfiles.o moc_recentfiles.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

.SUFFIXES:

